### ISSUE TITLE
Compiler error build using 0.3.0-alpha.1

### ISSUE THREAD

**Issue by xmclark** [tower-rs/tower#341]
Trying to run a binary app with dependency on `build 0.3.0-alpha.1` on windows with `cargo 1.39.0-nightly (22f7dd049 2019-08-27)` has a compiler error:
```
error[E0599]: no method named `poll_next` found for type `std::pin::Pin<&mut tokio_sync::mpsc::bounded::Receiver<message::Message<Request, <T as tower_service::Service<Request>>::Future>>>` in the current s
cope
   --> C:\Users\Mac\.cargo\registry\src\github.com-1ecc6299db9ec823\tower-buffer-0.3.0-alpha.1\src\worker.rs:118:65
    |
118 |         while let Some(mut msg) = ready!(Pin::new(&mut self.rx).poll_next(cx)) {
    |                                                                 ^^^^^^^^^ help: there is a method with a similar name: `poll_recv`

error: aborting due to previous error
```

Built with this Cargo.toml:
```
[package]
name = "test-tower"
version = "0.1.0"
authors = ["Mackenzie Clark <mackenzie.a.z.c@gmail.com>"]
edition = "2018"

[dependencies]
tower = "0.3.0-alpha.1"
```

An empty main function:
```
fn main() {
}
```

**Comment by LucioFranco** [comment]
@xmclark yup, somehow this go through the publish. I think there is something weird going on with feature flags that allow this to get through. I've prepared a `0.3.0-alpha.1a` release for buffer and will get that out ASAP. Thanks for reporting!

**Comment by LucioFranco** [comment]
@xmclark ok I've published a new alpha for tower and buffer that both work, thanks for reporting this :)
